# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Update_Field <- function(Field, New_Slice, n) {
    .Call(`_dynSBevo_Update_Field`, Field, New_Slice, n)
}

Create_Field <- function(N, d1, d2, d3) {
    .Call(`_dynSBevo_Create_Field`, N, d1, d2, d3)
}

dynSB_CheckConvergence <- function(J, J_old, piv, Pi, B, piv_old, Pi_old, B_old, it, tol_lk, tol_theta, maxit) {
    .Call(`_dynSBevo_dynSB_CheckConvergence`, J, J_old, piv, Pi, B, piv_old, Pi_old, B_old, it, tol_lk, tol_theta, maxit)
}

dynSB_compute_ELBO <- function(Y, piv, Pi, B, Tau1, TAU, Taum, n, k, TT) {
    .Call(`_dynSBevo_dynSB_compute_ELBO`, Y, piv, Pi, B, Tau1, TAU, Taum, n, k, TT)
}

dynSB_compute_derivatives <- function(Tau1, TAU, n, k, TT) {
    .Call(`_dynSBevo_dynSB_compute_derivatives`, Tau1, TAU, n, k, TT)
}

dynSB_Initial_Random <- function(n, k, TT) {
    .Call(`_dynSBevo_dynSB_Initial_Random`, n, k, TT)
}

dynSB_Initial_Deterministic <- function(Y, n, k, TT) {
    .Call(`_dynSBevo_dynSB_Initial_Deterministic`, Y, n, k, TT)
}

dynSB_VE_step <- function(Y, piv, Pi, B, Tau1, TAU, Taum, d1Taum, d2Taum, n, k, TT) {
    .Call(`_dynSBevo_dynSB_VE_step`, Y, piv, Pi, B, Tau1, TAU, Taum, d1Taum, d2Taum, n, k, TT)
}

dynSB_M_step <- function(Y, Tau1, TAU, Taum, n, k, TT) {
    .Call(`_dynSBevo_dynSB_M_step`, Y, Tau1, TAU, Taum, n, k, TT)
}

dynSB_compute_LogLik <- function(Y, piv, Pi, B, V, n, k, TT) {
    .Call(`_dynSBevo_dynSB_compute_LogLik`, Y, piv, Pi, B, V, n, k, TT)
}

dynSB_compute_Classification <- function(Taum, n, TT) {
    .Call(`_dynSBevo_dynSB_compute_Classification`, Taum, n, TT)
}

dynSB_VEM <- function(Y, k, sv, tol_lk, tol_theta, maxit) {
    .Call(`_dynSBevo_dynSB_VEM`, Y, k, sv, tol_lk, tol_theta, maxit)
}

dynSB_Update_step <- function(Y, k, sv, tol_lk, tol_theta, maxit) {
    .Call(`_dynSBevo_dynSB_Update_step`, Y, k, sv, tol_lk, tol_theta, maxit)
}

dynSB_LastUpdate_step <- function(Y, k, sv, tol_lk, tol_theta, maxit) {
    .Call(`_dynSBevo_dynSB_LastUpdate_step`, Y, k, sv, tol_lk, tol_theta, maxit)
}

dynSB_Mutation_step <- function(Tau1, TAU, n, k, TT, LMP, UMP) {
    .Call(`_dynSBevo_dynSB_Mutation_step`, Tau1, TAU, n, k, TT, LMP, UMP)
}

dynSB_TotalSelection_step <- function(P_a, P_b, P_c, fit_a, fit_b, fit_c) {
    .Call(`_dynSBevo_dynSB_TotalSelection_step`, P_a, P_b, P_c, fit_a, fit_b, fit_c)
}

dynSB_Selection_step <- function(P_Old, P_New, fit_Old, fit_New, keep_best) {
    .Call(`_dynSBevo_dynSB_Selection_step`, P_Old, P_New, fit_Old, fit_New, keep_best)
}

dynSB_Random_Initialization_step <- function(Y, n, k, TT, n_parents) {
    .Call(`_dynSBevo_dynSB_Random_Initialization_step`, Y, n, k, TT, n_parents)
}

dynSB_Kmeans_Initialization_step <- function(Y, n, k, TT, n_parents, LMP, UMP) {
    .Call(`_dynSBevo_dynSB_Kmeans_Initialization_step`, Y, n, k, TT, n_parents, LMP, UMP)
}

dynSB_SBM_Initialization_step <- function(Y, n, k, TT, n_parents, LMP, UMP) {
    .Call(`_dynSBevo_dynSB_SBM_Initialization_step`, Y, n, k, TT, n_parents, LMP, UMP)
}

dynSB_EVEM_step <- function(Y, k, PV1, tol_lk, tol_theta, n_parents, LMP, UMP, R, n, TT, keep_best) {
    .Call(`_dynSBevo_dynSB_EVEM_step`, Y, k, PV1, tol_lk, tol_theta, n_parents, LMP, UMP, R, n, TT, keep_best)
}

dynSB_EVEM <- function(Y, k, tol_lk, tol_theta, maxit, n_parents, LMP, UMP, R) {
    .Call(`_dynSBevo_dynSB_EVEM`, Y, k, tol_lk, tol_theta, maxit, n_parents, LMP, UMP, R)
}

